# looks for dockerfile in build, maps port on machine : to port in container
services:
  # name of container = backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - DOCKER=true
    networks:
      - app-network
    restart: unless-stopped

  # db:
    # image: postgres:latest
    # environment:
    #   user: user
    #   pass: pass
    # volumes:
    #   - postgres_data:/var/lub/postgresql/data

  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  frontend-prod:
    profiles: ["prod"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

# volume = folder for multi-container sharing
# volumes:
#   postgres data:

# can run multiple containers --> frontend service, db service --> move docker to project root or confusing routing

# docker-compose up --build

# can do in cloud with docker build cloud --> builds using cloud/cache, speeding up

# can setup eevrything with docker init instead